export const INCREASE_PRODUCT_COUNT = 'INCREASE_PRODUCT_COUNT';
export const DECREASE_PRODUCT_COUNT = 'DECREASE_PRODUCT_COUNT';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
